apiVersion: v1
kind: Service
metadata:
  namespace: centodiciotto-dev
  name: centodiciotto-ws
  labels:
    app: centodiciotto
    component: ws
spec:
  type: NodePort
  clusterIP: 10.96.60.130
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30130
     protocol: TCP
  selector:
   app: centodiciotto
   component: ws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: centodiciotto-dev
  name: centodiciotto-ws
  labels:
    app: centodiciotto
    component: ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: centodiciotto
  template:
    metadata:
      labels:
        app: centodiciotto
        component: ws
    spec:
      imagePullSecrets:
      - name: secret-docker-cred
      containers:
        - name: centodiciotto-ws
          image: ***REMOVED***:8081/centodiciotto-ws:2.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
